export const baselineConfig = {
  timeouts: {
    actionMs: 15_000,
    navigationMs: 45_000,
    menuStepMs: 5_000,
    appIdleNetworkMs: 2_000,
    appBusyMs: 45_000,
    searchResultsMs: 30_000,
    postCreateProfileReadyMs: 20_000,
    captureStabilizeMs: 700,
    tabClickStabilizeMs: 700,
    captureNetworkIdleMs: 1_500,
    angularStableMs: 3_000,
    busyIndicatorMs: 3_000,
    captureRetryAttempts: 4,
    captureRetryDelayMs: 600,
    domStablePollMs: 250,
    domStableChecks: 2,
  },

  navigation: {
    individualProfileMenuPaths: [
      ['Licensing', 'Individual'],
      ['Case Management', 'Individual'],
      ['Administrator', 'Individual'],
      ['Administration', 'Individual'],
    ],
  },

  workspace: {
    entityInfoTabPattern: '^Entity Information$',
    minProfileTabs: 2,
    readyTextPatterns: [
      'Return to Search',
    ],
    profileIdentifierPatterns: [
      '\\b(?:Individual|Licensee)\\s+I[Dd]\\b',
    ],
    nonWorkspacePagePatterns: [
      '\\bNew Individual\\b',
      '\\bIndividual Search\\b',
      '\\bSearch Results\\b',
      '\\bEnter Search Criteria\\b',
    ],
  },

  capture: {
    tabSelectors: [
      '[role="tab"]',
      'button[role="tab"]',
      'a[role="tab"]',
      '.nav-tabs a',
      '.nav-tabs button',
      '.nav-link[role="tab"]',
      'ul.nav li a.nav-link',
      '.tabs a',
      '.tabs button',
      '.tabset a',
      '.tabset button',
      '.ajax__tab_tab',
      '.ajax__tab_header span',
    ],
    sectionHeaderSelectors: [
      '.section-head-custom h2',
      '.section-head-custom h3',
      '.custom-search-text h2',
      '.custom-search-text h3',
      '.section-header',
      '.section-title',
      '.card-header',
      'legend',
      'h1',
      'h2',
      'h3',
      'h4',
    ],
    ignoredSectionHeaders: ['Search Results', 'Modify Individual Profile', 'View Individual Profile'],
    pageHeadingPatterns: [
      '^View Individual$',
      '^Modify Individual$',
      '^New Individual$',
      '^View Individual Profile$',
      '^Modify Individual Profile$',
      '^New Individual Profile$',
    ],
    fieldLabelMetadataPatterns: [
      '^Business Unit$',
    ],
    enableAdditionalInformationTab: false,
    fieldLabelSelectors: [
      'label',
      '.control-label',
      '.form-label',
      '.field-label',
      '.label-control',
      'span[id*="Label"]',
      'span[id*="label"]',
      'span[id*="lbl"]',
      'td.label',
      'td.form-label',
    ],
    ignoredFieldLabels: [
      'Search',
      'Save',
      'Cancel',
      'Reset',
      'Back',
      'Next',
      'Previous',
      'Application Type',
    ],
    ignoredFieldLabelPatterns: [
      '^Fields marked with asterisk',
      '^Welcome\\b',
      '^Aithent Licensing System Version\\b',
      '^Individual Name:',
      '^Name:',
      '^User Type\\s*:',
      '^\\d+$',
    ],
    ignoredInformativeTextPatterns: [
      '^You are associated with multiple business unit\\(s\\), please select Business Unit to open profile\\.?$',
    ],
    tableSelectors: [
      'table',
      '[role="table"]',
      '[role="grid"]',
    ],
  },
};
