// ============================================================
//  logger.js
//  🚫  DO NOT EDIT THIS FILE
//  Prints the comparison results to the terminal / Playwright
//  console during the test run.
// ============================================================


// ─────────────────────────────────────────────────────────────
//  printResults
//  Call after comparison buckets are built.
// ─────────────────────────────────────────────────────────────
export function printResults({ labelA, labelB, urlA, urlB, itemsA, itemsB, matched, missing, iconMismatch, extraB }) {

  const W = 60;
  const D = '─'.repeat(W);
  const E = '═'.repeat(W);

  console.log('\n' + E);
  console.log('  SIDEBAR COMPARISON RESULTS');
  console.log(`  Source   : ${labelA}  (${urlA})`);
  console.log(`  Comparing: ${labelB}  (${urlB})`);
  console.log(E);

  const textMatched = [...matched, ...iconMismatch.map(i => i.title)];
  console.log(`\n✅  TEXT MATCHED (${textMatched.length})`);
  console.log(D);
  textMatched.length === 0
    ? console.log('    None')
    : textMatched.forEach(m => console.log(`    • ${m}`));

  console.log(`\n⚠️   MISSING / TEXT MISMATCH in ${labelB} (${missing.length})`);
  console.log(D);
  missing.length === 0
    ? console.log('    None')
    : missing.forEach(m => console.log(`    • ${m}`));

  console.log(`\n🔶  ICON MISMATCH in ${labelB} (${iconMismatch.length})  — text matched, icon differs`);
  console.log(D);
  iconMismatch.length === 0
    ? console.log('    None')
    : iconMismatch.forEach(({ title, iconA, iconB }) => {
        console.log(`    • ${title}`);
        console.log(`        ${labelA} icon: "${iconA || '(none)'}"`);
        console.log(`        ${labelB} icon: "${iconB || '(none)'}"`);
      });

  console.log(`\n🔵  EXTRA (${extraB.length})`);
  console.log(D);
  extraB.length === 0
    ? console.log('    None')
    : extraB.forEach(t => console.log(`    • ${t}`));

  console.log('\n' + E);
  console.log(`\n  Total in ${labelA}: ${itemsA.length}  |  Total in ${labelB}: ${itemsB.length}`);
  console.log(`  Text Matched: ${textMatched.length}  |  Missing/Text Mismatch: ${missing.length}  |  Icon Mismatch: ${iconMismatch.length}  |  Extra: ${extraB.length}\n`);
  console.log(E);
}
