// ============================================================
//  CompareSidebar.spec.js
//  🚫  DO NOT EDIT THIS FILE
//
//  Main test entry point. Orchestrates login → scrape →
//  compare → log → annotate.
//
//  To configure environments, edit config.js only.
//
//  Run:         npx playwright test CompareSidebar.spec.js
//  View report: npx playwright show-report
// ============================================================

import { test, chromium }  from '@playwright/test';
import { CONFIG }           from './config/url.js';
import { getSidebarItems }  from './core/scraper.js';
import { printResults }     from './utils/logger.js';
import { attachReport }     from './utils/annotations.js';
import { openGeneratedReports } from './utils/openArtifacts.js';
import { writeExcelReport } from './reporters/excelReporter.js';
import { writeHtmlReport }  from './reporters/htmlReporter.js';
import runSettings          from './config/runSettings.json' with { type: 'json' };


test('Sidebar Comparision', async ({}, testInfo) => {
  const basePayload = {
    labelA: CONFIG.urlA.label,
    labelB: CONFIG.urlB.label,
    urlA: CONFIG.urlA.loginUrl,
    urlB: CONFIG.urlB.loginUrl,
  };
  const generatedReports = {};

  async function writeAndAttachReports(payload) {
    await attachReport({ testInfo, ...payload });
    generatedReports.excelPath = await writeExcelReport(payload);
    generatedReports.htmlPath = await writeHtmlReport(payload);

    if (runSettings.attachReports) {
      await testInfo.attach('Sidebar Comparison Excel Report', {
        path: generatedReports.excelPath,
        contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      });

      await testInfo.attach('Sidebar Comparison HTML Report', {
        path: generatedReports.htmlPath,
        contentType: 'text/html',
      });
    }
  }

  let browser;

  try {
    browser = await chromium.launch({
      headless : runSettings.headless,
      slowMo   : Number(runSettings.slowMo ?? 0),
      args     : [
        '--ignore-certificate-errors',
        ...(runSettings.maximizeWindow ? ['--start-maximized'] : []),
      ],
    });

    // ── 1. Scrape both environments in parallel ───────────────
    const [itemsA, itemsB] = await Promise.all([
      getSidebarItems(browser, CONFIG.urlA),
      getSidebarItems(browser, CONFIG.urlB),
    ]);


    // ── 2. Build lookup maps ──────────────────────────────────
    const mapA = new Map(itemsA.map(item => [item.title.toLowerCase(), item]));
    const mapB = new Map(itemsB.map(item => [item.title.toLowerCase(), item]));

    // ── 3. Compare ────────────────────────────────────────────
    const matched      = [];   // A title — text + icon identical in both
    const missing      = [];   // A title — absent in B or text mismatched
    const iconMismatch = [];   // A title — text matches but icon differs
    const extraB       = [];   // B title — exists in B but not in A

    for (const a of itemsA) {
      const b = mapB.get(a.title.toLowerCase());

      if (!b) {
        missing.push(a.title);
        continue;
      }

      const textMatch = a.text     === b.text;
      const iconMatch = a.iconCode === b.iconCode;

      if (textMatch && iconMatch) {
        matched.push(a.title);
      } else if (textMatch && !iconMatch) {
        iconMismatch.push({ title: a.title, iconA: a.iconCode, iconB: b.iconCode });
      } else {
        missing.push(a.title);
      }
    }

    for (const b of itemsB) {
      if (!mapA.has(b.title.toLowerCase())) {
        extraB.push(b.title);
      }
    }

    const payload = { ...basePayload, itemsA, itemsB, matched, missing, iconMismatch, extraB };

    // ── 4. Print to terminal ──────────────────────────────────
    printResults(payload);

    // ── 5. Attach annotation to Playwright HTML report ────────
    await writeAndAttachReports(payload);

    // ── Test always passes — full results are in the annotation ──

  } catch (error) {
    const errorText = error?.stack || error?.message || String(error);

    if (!generatedReports.excelPath && !generatedReports.htmlPath) {
      const failurePayload = {
        ...basePayload,
        itemsA: [],
        itemsB: [],
        matched: [],
        missing: [],
        iconMismatch: [],
        extraB: [],
        error: errorText,
      };

      try {
        await writeAndAttachReports(failurePayload);
      } catch (reportError) {
        console.error(`Unable to write SidebarComparison failure reports: ${reportError?.message || reportError}`);
      }
    }

    throw error;
  } finally {
    await browser?.close();
    const reportOpenOptions = resolveReportOpenOptions(runSettings);
    if (reportOpenOptions.openHtml || reportOpenOptions.openExcel) {
      await openGeneratedReports(generatedReports, console, reportOpenOptions);
    }
    console.log('\n🔒  Browser closed — all sessions terminated.');
  }

});

function resolveReportOpenOptions(settings) {
  const legacyFallback = settings.openReports === undefined
    ? true
    : asBoolean(settings.openReports, true);

  return {
    openHtml: asBoolean(settings.openHtmlReport, legacyFallback),
    openExcel: asBoolean(settings.openExcelReport, legacyFallback),
  };
}

function asBoolean(value, fallback) {
  if (value === undefined || value === null || value === '') {
    return fallback;
  }

  if (typeof value === 'boolean') {
    return value;
  }

  const normalized = String(value).trim().toLowerCase();
  if (['true', '1', 'yes', 'y'].includes(normalized)) return true;
  if (['false', '0', 'no', 'n'].includes(normalized)) return false;

  return fallback;
}
